CREATE TABLE IF NOT EXISTS VARIABLE_SERVICES
(
    VARIABLE_ID INT,
    SERVICES_NAME TEXT,
    PRIMARY KEY (VARIABLE_ID, SERVICES_NAME),
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE(ID),
    FOREIGN KEY (SERVICES_NAME) REFERENCES SERVICES(NAME)
);