ALTER TABLE CONSTANT
ALTER COLUMN VAL TYPE NUMERIC;

-- Change type Total_TWh: VARCHAR -> NUMERIC
ALTER TABLE GLOBALENERGYMIX
ADD COLUMN Total_TWh_2 NUMERIC;

UPDATE GLOBALENERGYMIX
SET Total_TWh_2 = CAST(Total_TWh AS NUMERIC);

ALTER TABLE GLOBALENERGYMIX
DROP COLUMN Total_TWh;

ALTER TABLE GLOBALENERGYMIX
RENAME COLUMN Total_TWh_2 TO Total_TWh;