
-- EC2
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Elastic Compute Cloud (EC2)' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Elastic Compute Cloud (EC2)' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

-- FARGATE
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'AWS Fargate' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'AWS Fargate' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

-- S3
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Simple Storage Service (S3)' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- RDS
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Relational Database Service (RDS)' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Relational Database Service (RDS)' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Relational Database Service (RDS)' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- EFS
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Elastic File System (EFS)' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- AURORA
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Aurora' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Aurora' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Aurora' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- DYNAMO DB
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon DynamoDB' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- REDSHIFT
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Redshift' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Redshift' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'Amazon Redshift' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';

-- LAMBDA
INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'AWS Lambda' FROM VARIABLE as var
    WHERE var.NAME = 'MEMORY';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'AWS Lambda' FROM VARIABLE as var
    WHERE var.NAME = 'CPU_COMPUTE';

INSERT INTO VARIABLE_SERVICES(VARIABLE_ID, SERVICES_NAME)
SELECT var.ID, 'AWS Lambda' FROM VARIABLE as var
    WHERE var.NAME = 'STORAGE';