UPDATE VARIABLE SET FORMULA = 'storageCapacityInTo \times SSD\_POWER\_CONSUMPTION\_IN\_W\_PER\_TB',
  UPDATED_AT = CURRENT_DATE
  WHERE NAME = 'STORAGE';

UPDATE VARIABLE SET FORMULA = 'storageCapacityInGo \times POWER\_PER\_RAM\_GO',
  UPDATED_AT = CURRENT_DATE
  WHERE NAME = 'MEMORY';

UPDATE VARIABLE SET FORMULA = 'TDP\_FOR\_ONCE\_CPU\_CORE \times vCPUCores \times TDP\_TO\_POWER\_CONSUMPTION\_RATIO',
  UPDATED_AT = CURRENT_DATE
  WHERE NAME = 'CPU_COMPUTE';