
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('TDP_TO_POWER_CONSUMPTION_RATIO', 0.5, '', 'Le rapport entre l''enveloppe thermique et la consommation électrique');
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('POWER_PER_RAM_GO', 0.375, 'W/Go', 'La puissance consommée pour un Go de mémoire RAM');
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('SSD_POWER_CONSUMPTION_IN_W_PER_TB', 1.52, 'W/To', 'La puissance consommée pour un To de stockage SSD');

INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('TDP_FOR_ONCE_EPYC_CPU_CORE', 6.25, 'W', 'Le TDP pour un coeur cpu de type EPYC');
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('TDP_FOR_ONCE_XEON_CPU_CORE', 4.21875, 'W', 'Le TDP pour un coeur cpu de type XEON');
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('TDP_FOR_ONCE_GRAVITON_CPU_CORE', 1.5625, 'W', 'Le TDP pour un coeur cpu de type GRAVITON');
INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('TDP_FOR_ONCE_ETSY_CPU_CORE', 2.1, 'W', 'Le TDP pour un coeur cpu de type ETSY');

INSERT INTO SOURCE(NAME,LINK) VALUES ('Ratio usage', 'https://www.etsy.com/codeascraft/cloud-jewels-estimating-kwh-in-the-cloud');

INSERT INTO VARIABLE(NAME, DESCRIPTION, FORMULA, UPDATED_AT) VALUES ('STORAGE','', 'storageCapacityInTo \\times SSD\\_POWER\\_CONSUMPTION\\_IN\\_W\\_PER\\_TB', CURRENT_DATE);
INSERT INTO VARIABLE(NAME, DESCRIPTION, FORMULA, UPDATED_AT) VALUES ('MEMORY','', 'storageCapacityInGo \\times POWER\\_PER\\_RAM\\_GO', CURRENT_DATE);
INSERT INTO VARIABLE(NAME, DESCRIPTION, FORMULA, UPDATED_AT) VALUES ('CPU_COMPUTE','', 'TDP_FOR_ONCE_CPU_CORE \\times vCPUCores \\times TDP\\_TO\\_POWER\\_CONSUMPTION\\_RATIO', CURRENT_DATE);

INSERT INTO VARIABLE_SOURCE(VARIABLE_ID, SOURCE_ID)
SELECT var.ID, source.ID FROM VARIABLE as var, SOURCE as source WHERE var.NAME = 'CPU_COMPUTE' AND source.NAME = 'Ratio usage';

INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'CPU_COMPUTE' AND const.NAME = 'TDP_TO_POWER_CONSUMPTION_RATIO';
INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'CPU_COMPUTE' AND const.NAME = 'TDP_FOR_ONCE_EPYC_CPU_CORE';
INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'CPU_COMPUTE' AND const.NAME = 'TDP_FOR_ONCE_XEON_CPU_CORE';
INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'CPU_COMPUTE' AND const.NAME = 'TDP_FOR_ONCE_GRAVITON_CPU_CORE';
INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'CPU_COMPUTE' AND const.NAME = 'TDP_FOR_ONCE_ETSY_CPU_CORE';

INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'STORAGE' AND const.NAME = 'SSD_POWER_CONSUMPTION_IN_W_PER_TB';

INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'MEMORY' AND const.NAME = 'POWER_PER_RAM_GO';