INSERT INTO CONSTANT(NAME, VAL, UNIT, DESCRIPTION) VALUES ('MINIMAL_NUMBER_OF_REPLICATIONS_FOR_S3_STANDARD', 3, '', 'Nombre minimal de replication pour un service S3 standard');

INSERT INTO VARIABLE_CONSTANT(VARIABLE_ID, CONSTANT_ID)
SELECT var.ID, const.ID FROM VARIABLE as var, CONSTANT as const WHERE var.NAME = 'STORAGE' AND const.NAME = 'MINIMAL_NUMBER_OF_REPLICATIONS_FOR_S3_STANDARD';