UPDATE services
set SHORT_NAME='SAGEMAKERNOTEBOOK'
WHERE name = 'Amazon SageMaker';

INSERT INTO COMPATIBLE_INSTANCES_FOR_SERVICE(SERVICE_SHORT_NAME, INSTANCE_TYPE_NAME)
VALUES ('SAGEMAKERNOTEBOOK', 't3.medium'),
       ('SAGEMAKERNOTEBOOK', 't3.large'),
       ('SAGEMAKERNOTEBOOK', 't3.xlarge'),
       ('SAGEMAKERNOTEBOOK', 't3.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.large'),
       ('SAGEMAKERNOTEBOOK', 'm5.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.large'),
       ('SAGEMAKERNOTEBOOK', 'm5d.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'm5d.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.large'),
       ('SAGEMAKERNOTEBOOK', 'c5.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.9xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.18xlarge'),
       ('SAGEMAKERNOTEBOOK', 'c5.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.large'),
       ('SAGEMAKERNOTEBOOK', 'r5.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'r5.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p3.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p3.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p3.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p3dn.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p4d.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'p4de.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g4dn.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.2xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.4xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.8xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.12xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.16xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.24xlarge'),
       ('SAGEMAKERNOTEBOOK', 'g5.48xlarge');

UPDATE services SET Availability = 'Avilable' where services.name='Amazon SageMaker Notebook';

