CREATE TABLE IF NOT EXISTS CONSTANT(
   ID SERIAL PRIMARY KEY,
   NAME TEXT UNIQUE NOT NULL,
   VAL REAL NOT NULL,
   UNIT TEXT NOT NULL,
   DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS SOURCE(
   ID SERIAL PRIMARY KEY,
   NAME TEXT NOT NULL,
   LINK TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS VARIABLE(
   ID SERIAL PRIMARY KEY,
   NAME TEXT NOT NULL,
   DESCRIPTION TEXT,
   FORMULA TEXT NOT NULL,
   UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS VARIABLE_SOURCE(
    VARIABLE_ID INT,
    SOURCE_ID INT,
    PRIMARY KEY (VARIABLE_ID, SOURCE_ID),
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE(ID),
    FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE(ID)
);

CREATE TABLE IF NOT EXISTS VARIABLE_CONSTANT(
    VARIABLE_ID INT,
    CONSTANT_ID INT,
    PRIMARY KEY (VARIABLE_ID, CONSTANT_ID),
    FOREIGN KEY (VARIABLE_ID) REFERENCES VARIABLE(ID),
    FOREIGN KEY (CONSTANT_ID) REFERENCES CONSTANT(ID)
);
