name: 'iro-calc-back-local'

services:
  database:
    image: postgres:16-alpine
    container_name: irocalc-db
    environment:
      - POSTGRES_DB=Iroco2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5432:5432"
