name: 'iro-calc-back-local'

services:
  database:
    image: postgres:16-alpine
    container_name: irocalc-db
    environment:
      - POSTGRES_DB=Iroco2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5432:5432"

  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs,s3,lambda,ssm,logs,iam,events
      - DEFAULT_REGION=eu-west-3
      - AWS_DEFAULT_REGION=eu-west-3
      - DEBUG=1
      - DATA_DIR=/var/localstack/data
      - LAMBDA_EXECUTOR=docker
    ports:
      - '4566:4566'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
